### ISSUE TITLE
Long pauses when using automode.

### ISSUE THREAD

**Issue by Knurek-NC** [07th-mod/umineko-answer#14]
I think the question patch had the same issue initially, not sure though, it's been years. :)
Each voiced line has a 2-5 second delay after the sample stops playing. This makes using the automode a chore at best and downright annoying at worst.

**Comment by drojf** [comment]
So, I played around with automode and found it works like this:

- The `automode_time` keyword sets the delay at the end of each line at the top of the script, you can set the `automode_time -50` to `automode_time 1000` to wait 1 second after the text has finished (i have updated the current script to use this setting)
- The game will wait for voices to finish before advancing, however the voices have been cut very close to when the sound ends, so it's a bit too fast. Not sure of an easy way to set that kind of delay.
- I assume with negative numbers, that's the amount of delay per character in automode. This would explain why you get variable delay with the original settings

I've set  `automode_time 1000` in the latest script file, seems to work well given that the lines are voiced. But you can change it to whatever you like.

You might also want to change the `defaultspeed 40,20,0` line if the text advances too slowly/quickly.
