### ISSUE TITLE
A few missed voice lines

### ISSUE THREAD

**Issue by TaylorHyuuga** [07th-mod/umineko-answer#21]
There were a few voice lines around the start of Episode 6 (Namely, a few lines by Bernkastel, don't remember them, and "At least your naming sense is <good>, Battler-san. I'll give you that much) that didn't play. It wasn't the glitch that sometimes cancels out the voice clips at the start, since I was in auto mode and, in my experience, auto mode doesn't cause that glitch, plus they just never played at all, not that it started and then cut off after a second like the other times it has happened for me.

**Comment by TaylorHyuuga** [comment]
Some more lines, also early on in Episode 6, that are the same way, said by Genji: "Though truly, you have displayed such skill. It is hard to believe that this is your first time.  ...I believe even Erika-sama will be satisfied with this game"

**Comment by DoctorDiablo** [comment]
Sorry for the slow reply, I was out of town this weekend.

I found a pattern in the issues you identified and was able to find 15 separate lines that were missing the voices.  Just pushed a fix for all of them, you can grab the latest 0.utf and drop it in your Umineko Chiru folder.

I'm going to mark this issue closed, but feel free to reopen it if you run into any other issues with the voices.

**Comment by drojf** [comment]
OK for the first one, it appears that the inserter didn't insert any voices for that line:

``` langen^  At least your naming sense is <good>, Battler-san.^@^  I'll give you that much."^\ ```

The old umitweak line is

```dwave 0, "voice\46\64500057.ogg"`At least your title is <good>, Battler-san. I'll give you that much."`\```

It appears that the voice line "voice\46\64500057.ogg" (sequentially the next number in the script) is missing, so I'll put that in for that line.

The second problem you reported is the same

```langen^  ...Though truly, you have displayed such skill.^@^  It is hard to believe that this is your first time.^@^  ...I believe even Erika-sama will be satisfied with this game."^\ ```

the old umitweak line is:

```dwave 0, "voice\14\61600004.ogg"`......And yet, you have displayed such skill, It is hard to believe that this is your first time.`@dwave 0, "voice\14\61600005.ogg"`......I believe even Erika-sama will be satisfied with this game."`\```

@DoctorDiablo - I might make a script to index all the .ogg numbers used in the umitweak script, then check they exist in the current script. Does that sound reasonable? Not sure if you've done this already when you did your insertion script.

**Comment by drojf** [comment]
welp I was too slow @DoctorDiablo. but do you think it's still worth making that checking script?

**Comment by DoctorDiablo** [comment]
@drojf The voice inserter keeps track of every voice file it finds and at the end it puts together a list of potential issues.  If a file is used more than once, it gets flagged.  And if there are any gaps in the list (voice\14\61600003.ogg and voice\14\61600005.ogg are used, but not voice\14\61600004.ogg) it flags those too.  There were around 2000 errors in the list.  Many were duplicates and false positives, but I still had to manually fix a lot of them, and manual updates are the most error prone.

Not sure how these slipped through the cracks, but if these did then there could be others.  So anything you can run that would identify other issues would be great.

**Comment by TaylorHyuuga** [comment]
I can't seem to install the 0.utf. Am I doing it right? I go to the main Answer Arc page, click 0.utf, then click download, and it takes me to a completely different page and doesn't download.

**Comment by ItaloKnox** [comment]
@TaylorHyuuga if by different page you mean Github is actually opening the file in your browser (as text) instead of prompting you to download it, just hit ctrl+s to save it. Or go back one page, right-click the download button and click on ``save as...``

**Comment by TaylorHyuuga** [comment]
Ah, thank you.

**Comment by drojf** [comment]
@DoctorDiablo  - I searched the umitweak script globally for things which looked like voice file paths, then I did the same for our current script and output 

what was missing. Results are in the text file below. It shows which line of the umitweak script (attached) contains the voice file which is missing in our script.

[voice files missing from current script.txt](https://github.com/07th-mod/umineko-answer/files/1633775/voice.files.missing.from.current.script.txt)

I've included the script I used in case the line numbers are different (assumes line numbers start from 0). Or you can just search the .ogg filenames. 
[umitweak_original.zip](https://github.com/07th-mod/umineko-answer/files/1633771/umitweak_original.zip)

If there are any items you're not sure about (for example, the ones around line 302249 onwards have been replaced in the new script and don't need to be inserted), just leave them. Once you've committed the changes to the repository then I'll just run the script again to see what is missing. 

Again, there are not that many missing, so if you are busy I can just fix them manually.

Script I used: https://gist.github.com/drojf/0104b6b23c5ec503dfd6e77b6a1df250

**Comment by DoctorDiablo** [comment]
Oh, that doesn't look too bad.  I should be able to clean those up today.  I'll let you know if I run into any problems.

And I'll reopen this issue so we don't lose track of it...

**Comment by TaylorHyuuga** [comment]
So, I did the thing that Italo told me to do, right clicked on the 0.utf download button and clicked "Save Link As", named it 0.utf, and put it in the Chiru folder, but that pushed everything to the right where I can't see or click on anything. I couldn't fix it, either. Even when I downloaded the master zip and dropped the UTF from there, it didn't do anything.

**Comment by ItaloKnox** [comment]
Did you remember to download the patched Umineko5to8.exe?

**Comment by TaylorHyuuga** [comment]
Where do I install that?

**Comment by ItaloKnox** [comment]
https://github.com/07th-mod/resources/releases/download/Bern/Umineko5to8.exe

Put it in your game folder.

**Comment by TaylorHyuuga** [comment]
Sweet, thanks

**Comment by TaylorHyuuga** [comment]
Another issue, I installed that exe, and now all of the backgrounds and sprites are just gone. Although that could be because something is missing somehow, since I don't see any foders dedicated to sprites or backgrounds. This is my folder, if you want to take a look
![image](https://user-images.githubusercontent.com/34898938/35026910-f7150112-fb0a-11e7-84b3-5b98c198c553.png)

**Comment by ItaloKnox** [comment]
Okay, I guess I understand what is going on. From the looks of your folder, you were playing the game with voices only, right?

Then you need this [0.utf](https://github.com/07th-mod/umineko-answer/raw/master/voices-only/0.utf) (right click, save link as...) and don't need the .exe. You might want to ask Steam to verify the game cache in case you didn't backup it.

**Comment by TaylorHyuuga** [comment]
I mean, seeing as how there isn't a graphics patch available yet, course it's voices only. I will try that,

**Comment by ItaloKnox** [comment]
Actually, we're testing the graphics patch internally (available only for Discord members for now), so I thought you were one of them. My bad.

**Comment by TaylorHyuuga** [comment]
Yeah, no. I'm only here. Otherwise, I probably would be asking for assistance on the Discord instead of using an issues page that I just happened to make that isn't related to my current issue :P

**Comment by ItaloKnox** [comment]
Well, actually Discord issues are mostly related to immediate assistance and every other issue is recommended to be here. Just a misunderstanding, I guess.

**Comment by TaylorHyuuga** [comment]
Yeah, I would certainly call my issues an "immediate issue". The specific voice lines not playing isn't, but my various other issues are immediate, I'd say. Also, I had Steam verify the cache, and the voices stopped working. I put in the  0.utf, and everything was to the right again. I don't know the issue.

**Comment by ItaloKnox** [comment]
Immediate assistance on the same level of "I don't know how to extract the patch", or "I don't know how to download". In fact, I just misunderstood what you were saying because you said:

> that pushed everything to the right where I can't see or click on anything. I couldn't fix it, either. Even when I downloaded the master zip and dropped the UTF from there, it didn't do anything.

The instruction I gave you was right, you just picked the wrong file. :P

**Comment by TaylorHyuuga** [comment]
Ohhhhh, I think I understand. So drop the 0.utf from the voices only file, instead of the one in the master file, then? And it worked! Sweet, thank you for being patient with me.

**Comment by ItaloKnox** [comment]
Exactly. 👍

**Comment by drojf** [comment]
I think this is closed now, haven't had any voice problems for a while. We also ran a scan to check for bad or missing voice lines, which should have caught any further problems.
