### ISSUE TITLE
Graphical Bugs Chapter 6

### ISSUE THREAD

**Issue by Jellefishh** [07th-mod/umineko-answer#25]
These are screenshots of bugs I found in my testplay of chapter 6. I haven't finished chapter 6 yet, so I will add new ones here if I find them.

Apologies if these have been fixed already. I'm posting them because I haven't seen them mentioned before.

<img width="1440" alt="kumasawa wrong sprite" src="https://user-images.githubusercontent.com/35735649/35283490-b33e5c6a-0058-11e8-8f8e-af3c9eeae297.png">
This wrong sprite appears shortly after the 2 Beatrice's meet for the first time.  

**drojf - this has been fixed a while ago**

<img width="1440" alt="kanon vs maria 1" src="https://user-images.githubusercontent.com/35735649/35283527-c667ed24-0058-11e8-8564-edf5953664e8.png">
I've experienced this one several times. It doesn't play on the entire screen whenever it's used, not just here. This occasion I found it during the Kanon vs Maria fight during the first twilight. It happens at the start of the fight.

**drojf - I think I got most of these fixed. Is this the effect which plays when the stakes are clanging around the room?**

<img width="1440" alt="kanon vs maria 2" src="https://user-images.githubusercontent.com/35735649/35283581-ee4badf8-0058-11e8-936c-808a0cf2bc96.png">
During the same fight, the screen isn't completely filled with the 'black layer'. Missing a piece at the bottom.

**drojf - this and other instances of it has been fixed recently**

<img width="1440" alt="kanon vs maria 3" src="https://user-images.githubusercontent.com/35735649/35283643-208fedc4-0059-11e8-9681-1709f228100f.png">
Another one in the Kanon fight. The effect only plays in a small section of the window. The same effect doesn't work in other fights either.

<img width="1440" alt="shannon vs maria" src="https://user-images.githubusercontent.com/35735649/35283716-4c82c4ce-0059-11e8-8dd1-495eb9b42bcc.png">
This one happened during the next fight, Shannon vs Maria. Once the barrier starts expanding, it starts off at a wrong position.

**drojf - this has fixed recently**

<img width="1440" alt="beatrice vs natsuhi 1" src="https://user-images.githubusercontent.com/35735649/35283806-7fe9699e-0059-11e8-8529-85e99f7fa9c8.png">
This one happened during the Beatrice vs Natsuhi scene. It's similar to what happened with the Kanon scene, missing a piece at the bottom.

**drojf - this and other instances of it has been fixed recently**

<img width="1440" alt="beatrice vs natsuhi 2" src="https://user-images.githubusercontent.com/35735649/35283892-adb4ddb8-0059-11e8-9315-55a45d83f4cf.png">
In the same scene, the tint of black changes with the next line of text.

**drojf - this is deliberate, it makes more sense when the black covers the whole screen. It's meant to be every time you click the screen becomes more black. The same effect is used in one other scene in the game when someone is injured.**

**Comment by drojf** [comment]
With regards to this bug [blade7_1r.png]: <img width="1440" alt="kanon vs maria 3" src="https://user-images.githubusercontent.com/35735649/35283643-208fedc4-0059-11e8-9681-1709f228100f.png">

The image we have actually looks like that, see below:
![capturea](https://user-images.githubusercontent.com/1249449/35509111-073685ac-0547-11e8-8a59-4084a469cdab.JPG)

It was bugging me too, so I checked umitweak's release and they had the same image in their game:
![hblade7_1r](https://user-images.githubusercontent.com/1249449/35509164-3b03d538-0547-11e8-9aa5-f38eee5f12d8.png)

----

With regards to the zoom effect, the spot you showed me was indeed broken. These sections used a custom command (jump_set) to set what image was used, and the value was hardcoded to the old game's backgrounds. There were 5 instances of this I fixed.

----

I'll leave this thread open so people can see these as most likely if they installed the game recently and havent' updated the script they will see the same bugs.

**Comment by drojf** [comment]
>the (#)2 is that during i think episode 6?
>when beato starts fading from the duel between kanon and shannon
>it switches to her pachinko sprite

I'm asking the error reporter to retrieve a screenshot, this post will be updated with it later if they get one. EDIT: found it, it's related to the `mld2` function. EDIT2: has been fixed in https://github.com/07th-mod/umineko-answer/commit/142d93dec212b16e566c8dc378c2f56c897ca57f

also reported



> another noteworthy scene was uhh the start of the fight when the goats show up in the 8th episode
> some of the stakes activating their swords bugged out
> and duped the blade effect
> so that there was one spawned incorrectly to the left of the correct one
> for whatever reason
> also they'd shift to their pachinko sprites a few times
> again not rly sure why

![hbld 2](https://user-images.githubusercontent.com/1249449/35615749-398ae86e-06c7-11e8-8246-c31995f7d486.jpg)

EDIT: fixed by commenting out the 'bld'  function - see  https://github.com/07th-mod/umineko-answer/commit/4d13591a1ae91accf516030a8d485cae2ec2c826

**Comment by drojf** [comment]
These should all be fixed now.
