### ISSUE TITLE
Pachinko/disappearing sprites when loading from a save

### ISSUE THREAD

**Issue by drojf** [07th-mod/umineko-answer#30]
When loading from a save, the pachinko sprites may appear, or no sprites may appear. However clicking to advance will load the new sprites. Not a big deal but I'll have to look at it.

**Comment by VLF100** [comment]
I can confirm this happens with the ps3 sprites as well. Loading a scene makes all sprites dissapear and oly load back when the sprite is loaded again (because it changes position or face etc)

**Comment by VLF100** [comment]
Furthermore, at least in chapter 8, loading a save make Stakes Sisters sprites appear (on top of the other sprites dissapearing), in scenes where they shouldnt even be. Example:
![20180203110246_1](https://user-images.githubusercontent.com/24494940/35766152-bb71130a-08d2-11e8-97ef-1fbee1c8bd32.jpg)

**Comment by drojf** [comment]
woops forgot to leave a comment on how it was fixed:

>To allow for new/old sprites, MG calls a function to restore the correct sprites after loading a savegame.
>This commit removes this step since we don't support old sprites..

The fix was to literally comment out one line of code `;changeSprites %is_old_sprites`, which is executed just after a save game finishes loading (in the function `*Coll_system`)
