### ISSUE TITLE
Typos in text Images

### ISSUE THREAD

**Issue by drojf** [07th-mod/umineko-answer#31]
(ba**tt**ler should have two t's , the error isn't that there are three e's)
![unknown](https://user-images.githubusercontent.com/1249449/35604074-83bf3ac6-0694-11e8-9579-1cbb6677ffe6.png)

Also this typo (ushiromiya):

![unknown](https://user-images.githubusercontent.com/1249449/35604142-e47a0418-0694-11e8-83cc-b3e25a3276e4.png)

**Comment by Forteissimo** [comment]
Fixed here, sorry for the mistake

[typos.zip](https://github.com/07th-mod/umineko-answer/files/1680467/typos.zip)

**Comment by drojf** [comment]
This issue should have been closed in Release v0.6.1 (asset only fix as per above zip file)
