### ISSUE TITLE
Disable rain when CGs displayed

### ISSUE THREAD

**Issue by drojf** [07th-mod/umineko-answer#32]
Disable rain when CGs displayed so it's easier to see them (unless it doesn't make sense)

**Comment by ctom42** [comment]
Should also disable the golden petal effect during the CG in that scene.
![cg petals](https://user-images.githubusercontent.com/2365513/35762783-7d691b3c-086b-11e8-9c84-27573931d0f4.png)

**Comment by drojf** [comment]
I'm hesitant to remove it for that CG because that's how it was in the PS3 version. For reference, see this video: https://www.youtube.com/watch?v=wva7GCAh9tQ&list=PLUC-2-WHEbNO6srqy0x42UXN9aX-xOezo&index=26 (spoiler for anyone who hasn't played that part of the game)

**Comment by andOlga** [comment]
List of current *known* CGs which are ruined by the rain:

- ep504
- ep703_a
- ep703_b
- ep803
- ep805
- ep805_a
- ep809_a
- ep809_b
- ep809_b_z

There *may* be more of these, but that will need closer investigation.
Current supposed fix:
1. Add `dllefe_off` right before the CG is loaded.
2. Add `dllefe 1,1` right after the CG is unloaded, if rain display still makes sense to do at that point.
