### ISSUE TITLE
A lot of strange issues

### ISSUE THREAD

**Issue by TaylorHyuuga** [07th-mod/umineko-answer#40]
So, I just installed the graphics and voice patch (using the auto installer) and booted up the game, and I started getting some odd issues. First, odd strings of text started going down the left side of the screen, it just said "/volY" followed by Japanese text. It did this whenever I did anything, clicked an option, moved the text forward, etc. Second, the transparent box and, subsequently, all of the text just went to the top left of the screen, while all of the sprites were where they would be normally. Third, while all of the backgrounds were changed, none of the sprites were. I don't think this would be an issue with the auto installation, since it said that it would either work perfectly or break the game and it hasn't done either, and the installer for the Question Arcs worked perfectly when I tried it. I will try the manual download just in case, though.

**Comment by TaylorHyuuga** [comment]
Never mind, I figured it out. I just had to verify the files, and then replace the 0.utf and executable.

**Comment by drojf** [comment]
hmm...i'm interested as to what happened though. The 0.utf is not verified because we update it too often so every time its updated we would need to update the verification file. For that file we just grab the latest script off github. So in theory if the download failed completely the 0.utf could be not complete or corrupted. And in some rare case, the game might actually run while missing part of the 0.utf. 

Usually the downloads from git only fail if the download time is so long, so it's not usually a problem with the 0.utf.

The exe is verified, so it shouldn't be responsible.

Could also be the recent steam update messing with it somehow.

**Comment by TaylorHyuuga** [comment]
There is a really odd issue where the opening movies become really tiny, go to the top left corner of the screen, and shows the original sprites. But, eh. I'm not even gonna TRY to fix that. I could just end up breaking everything even more.

**Comment by drojf** [comment]
it sounds like (to me) that steam overwrote your movies file. That means you need to re-extract the graphics.7z and it should fix it (only for the 2 opening movies). 

I should really take away the option to delete the installer zip files...or ask users to rename the game folder to prevent steam overwriting stuff.

**Comment by TaylorHyuuga** [comment]
I shall try that, then

**Comment by TaylorHyuuga** [comment]
Which download is it in? 1, 2, or 3?

**Comment by ItaloKnox** [comment]
@drojf Can't we change the filename for the movies so it doesn't get overwritten? We won't even need to recompile the graphics patch, I just have to set up a couple commands to rename the files while installing.

**Comment by drojf** [comment]
you can do it that way, but the 0.exe and the 0.utf are always at risk of being overwritten by a steam patch anyway.

If you want to change the movie filenames just let me know so I can update the script accordingly

@TaylorHyuuga  - I don't think you can open just one of the graphics archives - you need all 3 for it to extract properly.

**Comment by drojf** [comment]
it has been over a year so I'm closing this issue now.

various issues related to having old versions of the script etc. should be fixed with the new installer, and the file renaming (0.utf -> 0.u etc.) should fix the steam update issues.
