### ISSUE TITLE
Steam Update Fix - Alternate .exe

### ISSUE THREAD

**Issue by drojf** [07th-mod/umineko-answer#43]
So I believe I've patched the .exe so that it loads a different script (`0.u` instead of  `0.utf`), and saves to a different location (`mysav` instead of `saves`). This should prevent the user ever loading the wrong saves, regardless of which files are overwritten:

Case | Problem | User Action
-- | -- | --
exe overwritten | because   the .exe was overwritten, the save folder will be different, so the user   cannot load the wrong save file. | User   will need to re-copy .exe file.
0.utf overwritten | because   the .exe loads a different script, this has no effect | None
exe and 0.utf overwritten | because   the .exe was overwritten, the save folder will be different, so the user   cannot load the wrong save file. | User   will need to re-copy .exe and script.
neither overwritten | ok | None

also, wow, you can copy and paste a table from exel into github...

This results in the following procedure for existing users to update their installations:

1. Download the new .exe for their platform and overwrite the existing .exe
2. Rename their 0.utf script to 0.u
3. Rename the save folder from 'saves' to 'mysav'
4. Keep a backup of the .exe file and 0.u file incase it gets overwritten (mainly the .exe file, but 0.u too since many users could have many different versions of the file, possibly with incompatible saves)

The manual instructions for the normal and voice-only install requires these updates:

- tell users to download the new .exe
- tell users to rename the 0.utf to 0.u

The automatic installer should be modified as follows:

- the installer must be updated to rename the 0.utf to 0.u (probably easier than renaming the script in git)

With regards to the OP movie being overwitten:
- the installer for Chiru should rename the OP movies to prevent them being overwritten. ~~I also need to update the script to play the correct OP path (with fallback to the legacy path) - will let you know when that's done.~~ The updated Chiru script will now prefer `x.mpg.mpg` to `x.mpg` (for all movie files). So renaming the `umineko_op5.mpg` to `umineko_op5.mpg.mpg` will cause the game to prefer them instead of `umineko_op5.mpg`. 

- for manual installations...well I guess the easiest way would be to recompile the .zip file. You could tell users to rename the file but there's a chance they'll see the other movies in the folder which are spoiler. You could also just make another zip for users to download - it would be another 250mb approx.

Now, there are two games, each game supporting 3 different platforms. We also support both voiced and unvoiced versions of the game. This results in 12 different executables, which I've attached to this post.

[Patched_Executables.zip](https://github.com/07th-mod/umineko-answer/files/1750151/Patched_Executables.zip) (sorry for the double zip file - for some reason zip files don't compress between files, so you need to do it this way to get good compression ratio to fit under github's 10mb limit)

**Comment by ItaloKnox** [comment]
That looks great! I'll push the wiki and installer updates tomorrow since I'm going to bed really soon.
