### ISSUE TITLE
Option - old or mangagamer sprites with new  backgrounds and voices

### ISSUE THREAD

**Issue by drojf** [07th-mod/umineko-answer#45]
Experimental version which uses the old or mangagamer sprites, but the new backgrounds and voice:

- [X] updated script: https://github.com/07th-mod/umineko-answer/raw/old_sprites/0.utf
- [x] resized sprites [NO LINK]
- [ ] update the wiki
- [ ] confirmation it actually works properly (how about mld/meta world? does that work?)

**Comment by Petsnew** [comment]
Resized sprites: https://mega.nz/#!mZcAFLDL!gujplfJ1lj6qnnSjJ7w_9B8ZJBySTw1jHCVWBjXbMx4
I'll rework the zoomed sprites from scratch, so this is not final.

**Comment by drojf** [comment]
Just for the record, here's what I did with the 'zoom' sprites.

History:
1. The original game (07th expansion) did not have zoom sprites - they used the `lsp2` command to do zooms in-engine (the engine has poor scaling though). It's written as two commands, one after the other: 

- `;ld_p KIR_DefB1G` sets the $ld_pass variable (dunno how exactly that part works/why it's done that way...I guess so you can use the same sprite aliases as normal sprite commands.)


- `;lsp2 3,$ld_pass,-600,100,300,300,0`  this line means:
    - load into advanced sprite slot 3
    - the sprite in the variable $ld_pass
    - such that its center is at -600, 100
    - with x and y scaling of 300%
    - with full opacity


2. The umitweak mod presumably re-made the zooms with a 'zoom' folder and just directly showed the images with `mldz c,":a;zoom/ep6/97.png",0`. 
3. The mangagamer release also uses custom zoom images, however they use the function `lsp2manual 4,"rg1_akuwaraia2",-310,-60,-310,-60,-1,"200","1"` . I still don't understand the function properly, but it re-maps the string `"rg1_akuwaraia2"`, for example, to the correct zoom image, and then places it at the correct location on the screen.

Because re-making the mangagamer sprites 100% would have been difficult (I think @irlPM  started doing it, but we decided to stop? I don't remember), I decided to use the 'original' games method (method 1), except instead of scaling the images in engine, the images were just scaled outside of the engine (this was done by @irlPM).
 
Code wise, I did this by modifying all the lsp2manual functions calls in the script so one of the variables now is just the x-coordinate of the sprite. I then modified the lsp2manual function itself to place the sprite such that its center was a the specified x-coordinate. 

These changes are in commit 61dd2797f796fab1e3905f454c9eb786519d6988 . You can see I have just copied the first argument from the old `lsp2` function into the first argument of the `lsp2manual` function Keep in mind that I have changed how the lsp2manual function itself - it only ever uses the first variable - the rest are ignored.

```
 ;lsp2 4,":a;bmp\TATI\RG1\1\RG1_akuwaraiA2.bmp",150,420,-200,200,0   //first arg is 150
-lsp2manual 4,"rg1_akuwaraia2",-310,-60,-310,-60,-1,"200","1"   //mangagamer
+lsp2manual 4,"rg1_akuwaraia2",150,-60,-310,-60,-1,"200","1"   //drojf modified 
```

**Comment by drojf** [comment]
Closing - we have used a different method (just asset replacement) to implement ryukishi/pachinko sprites (has already been implemented)

Any further discussion should occur in https://github.com/07th-mod/umineko-question/issues/131
