### ISSUE TITLE
[Voice Only] - Video crashes the game (two reports)

### ISSUE THREAD

**Issue by drojf** [07th-mod/umineko-answer#48]
I had a report from one user that the voice only video crashes the game when you play it. I couldn't reproduce it on my own computer with the latest video  files

The voice only video file is directly taken from the original umitweak release - we did this so that there were voices in a sequence which is normally just animated in the engine (which did not have voices). We couldn't re-encode the video we are using for the main patch because it is 16:9 resolution (well we could, but we would have to crop the video).

If any users come across this issue, please let us know, I can't really tell if it's a once off kind of issue or not.

**Comment by Petsnew** [comment]
I'm going to start ep8 today, I'll report if I get the same issue.

**Comment by drojf** [comment]
OK, debugged this issue with a user. Could reproduce after user sent save file to me, I loaded the save file, and played the video.

In short, it looks like the video file is way too big. smaller video files play fine. I checked that it wasn't some codec setting by making FFMPEG loop the opening video 6 times for a 600mb file, which promptly crashed the game.

Using the same encode settings we used for the PS3 patch should fix this problem (currently the file is 480mb , would want something like 100-120mb).

**Comment by drojf** [comment]
I tested the new video file on my own machine, and also asked the user who reported it to test it (on the save file which causes the crash). Both worked just fine.

The user tested it from the new Update .zip file which I've already uploaded (it just replaces the old one)

EDIT: video settings:
```
ffmpeg -i ep8end_1080p.mpg   -c:v mpeg1video -bufsize 4096k -maxrate 60000k -qscale:v 1 -vf "crop=1440:1080:240:0, scale=-1:480" -sws_flags lanczos -c:a copy ep8end.mpg
```
# WARNING - these video settings don't appear to work for question arcs? I think if maxrate/bufsize is set, it somehow breaks the video for the game....

Resulted ina  ~100mb file. Not sure how we got a 500mb file before...
