### ISSUE TITLE
Only PlayStation 3 Sprites in Answer-Arc available?

### ISSUE THREAD

**Issue by WannabeChuunibyou** [07th-mod/umineko-answer#49]
Greetings!

Sorry that I bother you, but I'm hopefully new when it comes to modding and I barely do modding. Last year, it worked really well patching my Question-Umineko manually. I own a new Laptop for some time now and with the current Steam Summer Sale, I also bought Umineko-Answer. Since I haven't installed the game on my new Laptop so far, I was surprised that there is this handy installer now. Using Windows 10, it worked perfect with the first game and this Version of the patch is even better than the one I installed manually last year.

Have tried the same with the answer arc, worked so far without any issues but I'm not able able to select any other sprites than the PlayStation 3 sprites. When I'm going to change them and click the Icon in the game, the mini Icons of the original doujin artwork are displayed, but the ingame artworks don't change. They disappear quickly and then the one from the PlayStation 3 Version appear again.

Browsing through the threads here haven't gave me a clear answer if this is on purpose or if this is a bug. This would be strange because the first game works without flaws and even the second game installed without any problems.

I will use the new artowks anyway, but just to be safe that I play a stable version, can anyone confirm please that there aren't any other artworks to choose from?

If not, is there a tweak to fix it if this is a problem/bug?

**Comment by drojf** [comment]
Sorry, we really should update the documentation on this. 

We do have a version which lets you play with the old sprites. It hasn't been that well tested, but I haven't had anyone complain about any bugs either.

To use it, download the script file from here (right click download): https://github.com/07th-mod/umineko-answer/raw/old_sprites/0.utf

Rename it as `0.u`, and replace the existing `0.u` in your game directory.

Note that all the characters will appear a little smaller than usual. And in the case of the "old old" game sprites, their top of their heads may be cut off a little bit. This is due to the increased resolution of the game.

I'll update the wiki with this information.

**Comment by WannabeChuunibyou** [comment]
Many thanks for the reply drojf! Glad I decided to ask in the end. Yes, it is a Little conufsing especially for People who haven't followed the development of the patch for the Answer-Arc.

Will download the file. Do I have to install anything from the beginning or can I just follow your instructions here you provided?

**Comment by drojf** [comment]
I think all you need to do is replace the script file, no re-installation or other steps are required.

I don't think the saves are compatible though (it might skip you forward/backward in the game). Probably best to just start at the start of a chapter and skip forwards (use the CTRL key) if that is an issue.

The information has been added to the wiki here: https://github.com/07th-mod/guide/wiki/Umineko-Part-2-Other-Install-Configurations

**Comment by WannabeChuunibyou** [comment]
Worked perfectly : )
I hadn't had a save file anyway since I'm still playing the first game so that wasn't a problem when it comes to testing. I guess I decide when I play the Answer-Arc which Artworks I prefer. Don't have a problem that the designs are not in it's original size.

Thanks again for the quick help and have a nice weekend. You guys are doing a great Job here.
