### ISSUE TITLE
Double portrait CG

### ISSUE THREAD

**Issue by andOlga** [07th-mod/umineko-answer#54]
![image](https://user-images.githubusercontent.com/462484/51716514-1dbd6480-204e-11e9-90ed-b97ad83f5fcb.png)

Happens around the scene where Kinzo is hanging Beato's portrait.

**Comment by drojf** [comment]
I'm assuming answer arcs, right? Which episode? some text which occurs nearby would be useful (if you specify some text nearby, I don't need to know which episode even)

**Comment by andOlga** [comment]
Oh, my bad. This is episode 7. Unfortunately I don't have exact text for this scene, though these lines are somewhat close to it:

Golden hair.
Long hair.
A good figure.
...Yeah. Something like that.
That's what the new Beatrice will look like.

This is a rough approximation however, but this is the closest line to that scene that I have saved.

**Comment by drojf** [comment]
```
langjp　金髪で。@
langjp　髪が長くて。@
langjp　スタイルが良くて。@
langen^Golden hair.^@
langen^Long hair.^@
langen^A good figure.^@
br
langjp　……そう。@そんな感じ。@
langjp　それが、新しいベアトリーチェの姿です。\
langen^...Yeah.^@^  Something like that.^@
langen^That's what the new Beatrice will look like.^\
```

I think that's the section you're talking about...you have good memory to get it 100% correct

Around that section, I can't find anything which is wrong - infact, it displays "bg\new_portrait3.png" which is a completely different image which is shown in your screenshot. How long ago did you install the answer arcs? ...although it would have to have been like a year ago or longer

There is another scene where kinzo is hanging the portrait which seems like it could cause that problem, but when I played it on my computer I couldn't reproduce it.

That section is as follows:
```
langjp　夏妃は深くため息をつく。@
langen^Natsuhi took a deep breath.^@
br
langjp　敬愛する金蔵の気紛れとはいえ、@……屋敷の顔である玄関ホールに、それが飾られることには、強い抵抗があるようだった。\
langen^Though this was a whim of Kinzo's, a man she greatly respected,^@^ ...she seemed to resist the idea of hanging it right here in the entrance hall, the face of the mansion.^\

textoff
bg white,22
wait 2000

bg new_portrait1,9

lsp bgsp,new_portrait1,-128,-70
print 9

langjp　白いシーツが取り払われると、そこには、ドレス姿の美しい西洋女性の姿が現れる…。@
langjp　それは、女性の姿を描いた、巨大な肖像画だった……。\
langen^When the white sheet was pulled off, a Western woman wearing a beautiful dress came into view...^@
langen^It was a massive portrait of a woman...^\

csp bgsp
bg black,22
bg new_mhal_1co,24
```

In that section, it displays the background image, then over the top it displays another copy of it, but the first copy fades out when the second one is displayed.:
```
bg new_portrait1,9

lsp bgsp,new_portrait1,-128,-70
print 9
```

If you're not sure about your installation, could you send me your script file? The 0.u file in your game directory.

**Comment by drojf** [comment]
I managed to get some sort of overlay issue when I reverted to this commit (not the same as your screenshot): ab904cd7fb447f6fd54e0ed0b0fc5e9e62a0db3a

The next commit which fixes it, f6bc6416256e68c8aa180f9bdd37209c344fd1e8,  is dated 2018-02-07

I think it only coincidentally fixed it - if you use the same sprite twice, it appears to clear the old one. but if you use a different one (eg use `new_portrait`, then `portrait`), the two images will be overlaid over each other. 

however, it still doesn't look quite the same as your screenshot. perhaps i'm still not looking at the right section.

**Comment by andOlga** [comment]
This second section you have found is the correct one. I will send the 0.u in a bit, though I have definitely not had the mod installed for longer than a year. It must have been around the 10th of January, 2019, when I installed it.

**Comment by drojf** [comment]
I'll try re-installing my chiru installation at some point (incase I've done something to my installation during development which changed the behaviour somehow). Technically I can remove what "may" have caused the problem, since it's not meant to be in the script, and just happens to look nice the way it is now (the part where it loads the portrait twice).

You are running 'normal mode' right? not 'ADV mode'?

**Comment by andOlga** [comment]
I am running it without the ADV patch. I installed the patch with the automated Windows installer.
