### ISSUE TITLE
ADV mode - Episode 8 start - textbox position is wrong

### ISSUE THREAD

**Issue by andOlga** [07th-mod/umineko-answer#56]
This is happening every time during this scene.

![image](https://user-images.githubusercontent.com/462484/54057298-9265f000-4203-11e9-9a5f-6f93524816ce.png)

A current workaround for this is to open the "Volume" menu and close it again, which repositions the textbox correctly.

**Comment by drojf** [comment]
This is what I get on a fresh install: https://www.youtube.com/watch?v=CZELJ_XZXos&feature=youtu.be

Could you send me your `mysav` folder? Then I can test your exact setup. I can't seem to reproduce it, even if I complete the episode 7 teaparty, then go to episode 8.

Can you also send me the script you're using, just so I can be sure our scripts are the same?

I assume it's some error where the game thinks ADV mode is not turned on, but it's still trying to use the background image from ADV mode.

**Comment by andOlga** [comment]
Attaching the relevant files as well as a video of it happening for me.
[mysav.zip](https://github.com/07th-mod/umineko-answer/files/2947972/mysav.zip)

**Comment by drojf** [comment]
I could reproduce the bug when i used your save files.

There seemed to be a missing "start ADV section" function call at the start of ep 8 (the other episodes had it). Try this script (your saves will be compatible): https://github.com/07th-mod/umineko-answer/raw/adv_mode/0.utf    It fixes it on my computer.

**Comment by andOlga** [comment]
Can confirm that this fixed it. Thanks!
