### ISSUE TITLE
No voices after I completed 1/3rd of Episode 5, and it's buzzing extremely. I tried replacing the voice files and renaming them like I was asked to do but it still didn't fix the problem.

### ISSUE THREAD

**Issue by Reisquin** [07th-mod/umineko-answer#66]
Here is a template you can use for reporting bugs. It is just a suggestion - some items might not be relevant to your issue.

- [a description of the issue]
- [pictures of the issue (if applicable)]
- The bug occurs just after [text from when bug occurs] is shown on the screen
- My operating system is [Windows, MacOS, Linux]
- I installed the game [X Months ago]
- I am running the [Full Patch / Voice only patch]
- I installed the game [Manually / using the Automatic Installer]
- My computer is a [Gaming Beast / Laptop with Integrated Graphics]
- Add the `stderr.txt` and `stdout.txt` to the post, as described above.

For issues where the game crashes or behaves badly, it is extremely useful to get the game's error log. Newer auto-installations can simply double click the "Umineko5to8_DebugMode.bat" file to start the game in debug mode.

Once you have started the game in debug mode, just play until the game crashes or behaves badly, then submit the `stderr.txt` and `stdout.txt` to us (when game is started in debug mode, a folder will appear showing `stderr.txt` and `stdout.txt`).

If you're not sure if it's a bug, you can report it on our discord (but try not to post any spoilers, if possible).
We really appreciate your help!

**Comment by andOlga** [comment]
1. Please actually fill out the template correctly.
2. What are you refering to when you talk about "renaming" the voice files? Merely extract the arc4.nsa and arc5.nsa over your existing ones.

**Comment by Reisquin** [comment]
I did just that and it still didn't fix.

> 1. Please actually fill out the template correctly.
> 2. What are you refering to when you talk about "renaming" the voice files? Merely extract the arc4.nsa and arc5.nsa over your existing ones.

**Comment by drojf** [comment]
As far as I understand it from the discord chat, you were trying to install the mod on the wrong version of the game (the original Japanese release), which we don't support. 

I've also added an explicit warning on the 'introduction' page of the wiki that we do not support the original Japanese release of the game.

> This patch modifies the newest release of Umineko by MangaGamer, attempting to replicate the PS3 version of the game. It is compatible with both the Steam and DRM-free (from Mangagamer.com) versions of the game. It is not compatible with the old/original Japanese release of the game.

As you've resolved your issue on discord, I'll close this issue.
