### ISSUE TITLE
Voice Patch

### ISSUE THREAD

**Issue by TaylorHyuuga** [07th-mod/umineko-answer#7]
Hi. I'm trying to download the voice patch for the answer arcs, but I'm having an issue. When I try and download the "Voices" .zip, it gets about halfway done and gives me a failure saying "forbidden". Do you perhaps know a solution? Thanks.

**Comment by ItaloKnox** [comment]
Looks like your ISP is having trouble connecting to Github. I uploaded the voice patch in an alternative host. The link should be good for the next 14 days: https://transfer.sh/O9lb9/UminekoChiru-Voices.zip

**Comment by TaylorHyuuga** [comment]
Thanks, I'll see if it works.

**Comment by drojf** [comment]
You can also try a download manager (assuming it doesn't always stop at the half way point): http://ugetdm.com/downloads-windows

**Comment by TaylorHyuuga** [comment]
Yeah, I already tried a download manager

**Comment by TaylorHyuuga** [comment]
Well, it's downloading slower, but it seems like it's going to properly download. It's almost halfway done, which is more than it used to get.

**Comment by TaylorHyuuga** [comment]
And the download worked. Thanks.

**Comment by ItaloKnox** [comment]
Great! I'm sorry you didn't get it to work using Github, I'll see if I can get something done to avoid this in the future. :)
