### ISSUE TITLE
Easy way to access the chapter select menu, even if not unlocked

### ISSUE THREAD

**Issue by drojf** [07th-mod/umineko-answer#9]
Currently, if you don't have the saves (`global.sav` or `envdata`  ?) and want to skip forward to later chapters, or skip within the same chapter, you need to just play the game. You also (in some cases) can't load your old saves to skip forwards in the game, if the script has changed significantly. 

It would be nice to be able to access the 'jump' menu, and also to 'unlock' episodes without actually having to play through them.

**Comment by DoctorDiablo** [comment]
Isn't there already a mechanism for this?  On the chapter select screen there's a button that lets you release the locks on chapters 6-8.  If you unlock a chapter, it should allow you to do scenario jump in the previous chapter.  I suppose you'd still have to play through chapter 8 to unlock scenario jump there though.

**Comment by drojf** [comment]
you're right -_-
